language: c
compiler:
    - gcc
before_install:
    #- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install -qq libcunit1-dev
    - if [ "$CC" = "gcc" ]; then sudo apt-get install -qq gcc-4.8; export CC="gcc-4.8"; fi
script: 
    - make test
