language: c
compiler:
    - gcc
before_install:
    #- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get install libcunit1-dev
    - sudo apt-get install gcc-4.7
    - export CC="gcc-4.7"
script: 
    - make test
